product_key: omnibus-toolchain

slack:
  notify_channel: eng-services-alerts

github:
  maintainer_group:  chef/engineering-services

merge_actions:
  built_in:bump_version:
    ignore_labels: "Version: Skip Bump"
  built_in:update_changelog:
    ignore_labels: "Changelog: Skip Update"
  built_in:trigger_omnibus_release_build:
    ignore_labels: "Omnibus: Skip Build"
    only_if: built_in:bump_version
