product_key:
  - omnibus-toolchain
  - angry-omnibus-toolchain

slack:
  notify_channel:
    - releng-notify
    - omnibus-rfr

merge_actions:
  - built_in:bump_version:
      ignore_labels:
        - "Version: Skip Bump"
        - "Expeditor: Skip All"
  - built_in:update_changelog:
      ignore_labels:
        - "Changelog: Skip Update"
        - "Expeditor: Skip All"
  - built_in:trigger_omnibus_release_build:
      ignore_labels:
        - "Omnibus: Skip Build"
        - "Expeditor: Skip All"
      only_if: built_in:bump_version

# Subscription to workload action of pull request merge to master branch on
# omnibus-software project will allow us to trigger an uncached omnibus build
# for omnibus-toolchain and angry-omnibus-toolchain when the omnibus-software
# has modified software config files.
subscriptions:
  # chef/omnibus-software
  - workload: pull_request_merged:chef/omnibus-software:master:*
    actions:
      - built_in:trigger_omnibus_expcache_build:
          only_if_modified:
            - config/software/*
            - config/patches/*

  - workload: artifact_published:stable:omnibus-toolchain:*
    actions:
      - built_in:rollover_changelog
      - built_in:notify_chefio_slack_channels
